### ISSUE TITLE
Decide genre

### ISSUE THREAD

**Issue by AndyRN** [AndyRN/art#1]
https://blog.github.com/2018-11-01-game-off-2018-theme-announcement/
> You’re welcome to interpret the theme however you wish, but if you need some ideas to kickstart your creativity, think about how your game could:
> - Feature an imaginary mashup of animals plants, or other objects with associated strengths and weaknesses. Giraffeopotamuses anyone?
> - Crossover different game genres, such as a turn-based platformer, real-time roguelike, or tower defense rythm game.
> - Combine multiple visual styles, perhaps pixel art characters exploring photo-realistic worlds.
> - Include a composition of music styles and sound effects like bagpipes and breakbeats.
> - Mix genres like Comedy Horror and Weird West.
> - Be powered by alternative/multiple controls, button mashing meets mousing or mobile device interaction

**Comment by AndyRN** [comment]
So far, I like Richard's idea of a "Phase-based shooter", whether it uses an "Asteroids" or "Tanks" visual style it still sounds fun.

I can see it working like this.

### Movement phase
- Select direction of movement
- Select how far the movement will go

### Attack phase
- Select what weapon will be used
- Select what direction to fire the weapon (if applicable)

### Action phase
- The game plays out both player and AI movement and attack instructions simultaneously.

Rinse, repeat till a victor emerges!

**Comment by r-f-j-thomas** [comment]
An RTS where all the units are restricted to the movement pattern of a chess piece (eg diagonals, L shapes).

Would be pretty terrible, but might be fun?

**Comment by r-f-j-thomas** [comment]
A vertical shooter like space invaders mixed with tower defense mixed with RTS base building. You don't control any defending units directly. Instead you build a base that spawns defending units that attack autonomously

**Comment by tahsinhadi** [comment]
a platformer where skills are accessed via rhythmic input, using a sister app on your mobile phone.

**Comment by AndyRN** [comment]
> A vertical shooter like space invaders mixed with tower defense mixed with RTS base building. You don't control any defending units directly. Instead you build a base that spawns defending units that attack autonomously

This reminds me of a load of old flash games, but was a 2D scrolling "battlefield" with the bases either end. I like the space invader spin, though!

**Comment by AndyRN** [comment]
> a platformer where skills are accessed via rhythmic input, using a sister app on your mobile phone.

Hmm, how would we accept mobile phone input with Godot?

**Comment by tahsinhadi** [comment]
maybe ignore the mobile input and just have a musical number pad

**Comment by AndyRN** [comment]
1v1 dogfight simulator, but in space with planets dotted around which will introduce gravity to the situation?

**Comment by AndyRN** [comment]
Parkour 2D platformer race? A bunch of players start on one side and have to manage their "stamina" while reaching the other side faster than their opponents.
